### PR TITLE
Added wp_nav_menu to header

### PR DESCRIPTION
**Pull request by puredazzle**
Since we init the menu in `public/themes/wordplate/includes/menus/` it would be good to have the code for the menu in the `header.php`

### CODE REVIEW

**Comment by vinkla** [comment]
LGTM! Could you please squash your commits before merging?

**Comment by vinkla** [comment]
Merged!

**Comment by puredazzle** [comment]
Thanks man. Its a pleasure working with you

**Comment by vinkla** [comment]
Anytime!

**Pull request merged**
