### PR TITLE
Add Elixir Support

### LINKED ISSUE #114: Implement Elixir
What are the thoughts on implementing [Elixir](https://github.com/laravel/elixir) as compiler for SASS/LESS and JavaScript? It uses Gulp for compiling.

### PR DESCRIPTION
**Pull request by vinkla**
This closes #114

### CODE REVIEW

**Comment by vinkla** [comment]
The styles directory structure issue should be fixed in the next release of Elixir https://github.com/laravel/elixir/issues/199

**Comment by vinkla** [comment]
Version 3.0 of Elixir has been released. @puredazzle has the new release solved our problems?

**Comment by puredazzle** [comment]
@vinkla please see latest commit. all our problems have been solved.

**Comment by vinkla** [comment]
Looks good, could you maybe squash your commits?

**Pull request merged**
