### PR TITLE
Copy all assets from the packages you use into your theme assets directory automatically

### LINKED ISSUE #156: Inappropriate assets placing problem caused by the url processing feature
Usually, public folder is really the place all assets loaded but in wordpress case is different.

In wordpress our public assets directory is inside the theme.
`mix.setPublicPath('public/themes/wordplate');`

So, i found that bootstrap and ionicons miss place the fonts.

Temporarily, i do `mix.copy`. It fixed the problem but the assets now duplicated.

```
const theme_assets = 'public/themes/wordplate/assets';
mix.copy([
    `${theme_assets}/fonts/ionicons.eot`,
    `${theme_assets}/fonts/ionicons.svg`,
    `${theme_assets}/fonts/ionicons.ttf`,
    `${theme_assets}/fonts/ionicons.woff`,
    `${theme_assets}/fonts/ionicons.woff2`
  ], `public/fonts`);
```

Any idea to fix this?

### PR DESCRIPTION
**Pull request by ihsanberahim**
make sure setResourceRoot and setPublicPath pointing on the same directory
* close #156

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request. Though, this pull request isn't inline with the directory structure. What is this solving?

**Comment by ihsanberahim** [comment]
This solving issue #156

**Comment by vinkla** [comment]
Please clarify the issue from #156. We don't really understand what you're trying to solve.

**Comment by ihsanberahim** [comment]
Sorry. I find hard to explain. I try explain it again.

In my case, the package `ionicons`'s fonts pointed to the default location `public/fonts`. 

Actually the original `webpack.mix.js` copy all the required fonts info `public/themes/wordplate/assets/fonts`.

So, browser fail to load the fonts.

Yeah. That is the issue #156 about.

**Comment by vinkla** [comment]
Oh, I see. Please retarget this to the develop branch.

**Comment by vinkla** [comment]
Does this load the fonts from the resources directory or does it copy them into the public directory?

**Comment by ihsanberahim** [comment]
this load the fonts from the resources directory

**Comment by vinkla** [comment]
Oh, that isn't such a good idea since the fonts wont be loaded in the public directory. Maybe you can use the following snippet?

```js
mix.copy(`${resources}/fonts`, `${public}/fonts`);
mix.copy(`${resources}/images`, `${public}/images`);
```

**Comment by ihsanberahim** [comment]
Sorry. I missed explain and miss understod on your question.  Actually, it does copy them into the public directory automatically and load the from there.

**Comment by vinkla** [comment]
So this pull request is redundant?

**Comment by ihsanberahim** [comment]
Yes. If my fonts located in `resources/fonts`.
No because my fronts are inside the packages i used like `ioncions` and `bootstrap-sass` and etc.

**Comment by vinkla** [comment]
We have discussed this internally and have decided to not add this right now. We really appreciate you taking the time to make a pull request. If anyone else find this useful in the future we could revisit this pull request again.

**Pull request closed without merging**
