### PR TITLE
Update the blog description from config

### PR DESCRIPTION
**Pull request by puredazzle**
Set the blog description from the config file.

### CODE REVIEW

**Comment by vinkla** [comment]
Maybe we could add a default text like the default in WordPress? What happens if you edit this in WP settings? Which one is used?

**Comment by puredazzle** [comment]
@vinkla The whole idea with this pr is to remove the tagline as default, and then if you really want it to set it via the config. If you update the WP settings it will be reset to the config option as you save. Maybe we should disable the field?

**Comment by vinkla** [comment]
I think it really depends on the usecase. If we merge this. The users wont be able to set this by them selves and we lock this feature for everyone using WordPlate. Is it possible to just change the default text and use the one in the database by default?

**Comment by puredazzle** [comment]
@vinkla hmm, maybe we can have a boolean instead then? `show_description` or something?

**Comment by vinkla** [comment]
Not sure what is best here but maybe we could do something like this:
```php
if (get_bloginfo('description') === 'Just another WordPress site') {
   // Run the update script.
}
```

By doing this it will only be updated once (during installation). Though, then the description in the configuration only be executed once which isn't that nice.

Maybe we need to think this through once more before adding it.

**Comment by puredazzle** [comment]
@vinkla This is done in the framework. It's just the variable that needs to be set in the config.

**Comment by vinkla** [comment]
Yes, that is true.

**Pull request merged**
