### PR TITLE
Force permalinks structure

### PR DESCRIPTION
**Pull request by puredazzle**
Force permalink to display be `/%postname%/`.

### CODE REVIEW

**Comment by puredazzle** [comment]
Fixes #123

**Comment by vinkla** [comment]
I'd argue we should move this to the framework and add configuration for this.

**Comment by puredazzle** [comment]
@vinkla Ok, just being lazy.

**Comment by vinkla** [comment]
Haha :smile:

**Comment by puredazzle** [comment]
@vinkla could you please take a look now?

**Comment by vinkla** [comment]
LGTM, please squash your commits.

**Comment by puredazzle** [comment]
Okidoki

**Comment by vinkla** [comment]
What happened on this last commit?

**Pull request merged**
