### PR TITLE
Added laravel-mix 6.0 support

### PR DESCRIPTION
**Pull request by vinkla**
This pull request adds support for the upcoming version of Laravel Mix.

### CODE REVIEW

**Comment by fiskhandlarn** [comment]
browserslist's default value is `> 0.5%, last 2 versions, Firefox ESR, not dead`: https://github.com/browserslist/browserslist#queries

Maybe write this in `package.json` as per https://github.com/browserslist/browserslist#best-practices
```json
  "browserslist": [
    "defaults"
  ]
```

... or omit `"browserslist"` completely and reference users to browserslist docs in WordPlate's readme?

**Comment by vinkla** [comment]
I'm not sure. Adding the default value would mean support for IE11 for example. [We've used this configuration.](https://jamie.build/last-2-versions)

Default browserslist:

```
and_chr 85
and_ff 79
and_qq 10.4
and_uc 12.12
android 81
baidu 7.12
chrome 85
chrome 84
edge 85
edge 84
firefox 81
firefox 80
firefox 78
ie 11
ios_saf 14
ios_saf 13.4-13.7
ios_saf 13.3
ios_saf 12.2-12.4
kaios 2.5
op_mini all
op_mob 59
opera 71
opera 70
safari 14
safari 13.1
samsung 12.0
samsung 11.1-11.2
```

Current setup:

```
and_chr 85
and_uc 12.12
chrome 85
chrome 84
chrome 83
chrome 80
chrome 49
edge 85
edge 18
firefox 81
firefox 80
ios_saf 14
ios_saf 13.4-13.7
ios_saf 13.3
ios_saf 13.0-13.1
ios_saf 12.2-12.4
ios_saf 12.0-12.1
opera 70
safari 14
safari 13.1
samsung 12.0
samsung 4
```

**Comment by puredazzle** [comment]
LGTM. 

I think we should stick with our current setup for Browserslist. Adding default support for IE11, when we try to move away from IE11 seems a little bit counterproductive, and will result in larger files.

**Comment by fiskhandlarn** [comment]
You're right about IE11. Maybe add a note in the README.md referencing https://jamie.build/last-2-versions then? :)

**Comment by vinkla** [comment]
Merging this since it works fine locally. I know the new version of Laravel Mix isn't stable yet.

**Pull request merged**
