### PR TITLE
provide docker

### PR DESCRIPTION
**Pull request by Lenny4**
https://github.com/wordplate/wordplate/issues/281

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the suggestion @Lenny4! Please add this to a repo of your own and then we can link to your setup guide from the documentation.

**Comment by Lenny4** [comment]
@vinkla here is my repo with the docker integration: https://github.com/Lenny4/wordplate

Why you don't merge this pull request ?

**Comment by vinkla** [comment]
Maybe you could just keep the Docker files in your repository and write a guide on how to add them to WordPlate?

> Why you don't merge this pull request ?

I don't want to maintain a Docker integration.

**Comment by fiskhandlarn** [comment]
@Lenny4 You could also consider:

1. Using existing containers instead of making yet another Dockerfile
2. Use nginx over apache (faster)
3. Use mariadb over mysql (freer)
4. Use phpfpm over php (faster)

**Comment by Lenny4** [comment]
@fiskhandlarn 
1) Using existing containers instead of making yet another Dockerfile: not sure because I want to have xdebug enabled by default, so I need to install it directly on a custom Dockerfile
2) Use nginx over apache (faster) agree
3) Use mariadb over mysql (freer) agree
3) Use phpfpm over php (faster) agree

**Comment by fiskhandlarn** [comment]
@Lenny4 https://hub.docker.com/r/automattic/wordpress-xdebug for example.

**Pull request closed without merging**
